spring.application.name=order-service
spring.main.banner-mode=console

app.demo.enabled=true
app.demo.id=201
app.demo.email=student@example.com
app.demo.phone=+37360000000
app.demo.subtotal=1500.00

spring.profiles.active=dev