spring.application.name=order-service

# Шаг первый
spring.datasource.url=jdbc:postgresql://localhost:5432/orders
spring.datasource.username=student
spring.datasource.password=student

#spring.profiles.active=jdbc
spring.profiles.active=jpa

app.demo.enabled=true
app.demo.id=201
app.demo.email=student@example.com
app.demo.phone=+37360000000
app.demo.subtotal=1500.00


# Шаг второй
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Дополнительно, если хотите видеть bind-параметры Hibernate:
logging.level.org.hibernate.orm.jdbc.bind=TRACE